name: PMEM benchmark procedure
description: PMDK benchmarking procedure for self-hosted runners equipped with PMEM
inputs:
  benchmark:
    description: The name of the benchmark .cfg file to run.
    required: true
  pmembench_extra_args:
    description: Pmembench extra args
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Run the benchmark
      working-directory: src/benchmarks
      env:
        LD_LIBRARY_PATH: ../nondebug
        # PMEMOBJ_CONF: sds.at_create=0
      shell: bash
      run: |
        ./pmembench ${{ inputs.benchmark }}.cfg ${{ inputs.pmembench_extra_args }} \
          --file /mnt/pmem0/testfile.obj | tee /tmp/${{ inputs.benchmark }}.csv

    - name: Archive logs
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.benchmark }}.csv
        path: /tmp/${{ inputs.benchmark }}.csv
