# Validate on default OSes.
name: Main

on:
  workflow_dispatch:
  pull_request:

jobs:
  src_checkers:
    name: Source checkers
    runs-on: ubuntu-latest
    env:
      NDCTL_ENABLE: n
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3
      - name: Check licenses
        run: make -j$(nproc) check-license
      - name: Check style
        run: make -j$(nproc) cstyle

  basic_build:
    name: Basic build
    runs-on: ubuntu-latest
    env:
      NDCTL_ENABLE: n
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3
      - name: Build sources
        run: make -j$(nproc) test

  call-ubuntu:
    needs: [src_checkers, basic_build]
    uses: ./.github/workflows/ubuntu.yml
    name: Ubuntu

  call-centos:
    needs: [src_checkers, basic_build]
    uses: ./.github/workflows/centos.yml
    name: CentOS