# Run less frequently used OSes and checks.
name: Nightly

on:
  workflow_dispatch:
  schedule:
    # run this job at 23:00 UTC every other day
    - cron:  '0 23 */2 * *'
  push:
    tags:
      - '*'

env:
  CONFIGS_JSON: |
    [
      "OS=ubuntu OS_VER=22.04",
      "OS=opensuse-leap OS_VER=15",
      "OS=rockylinux OS_VER=8",
      "OS=rockylinux OS_VER=9",
    ]

jobs:
  in-tree:
    name: In-tree
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CONFIG: ${{ fromJSON(env.CONFIGS_JSON) }}
        TEST_BUILD: [debug, nondebug]
        include:
          # Building with clang is tested in a limited scope
          - CONFIG: OS=ubuntu OS_VER=22.04 PMDK_CC=clang PMDK_CXX=clang++
            TEST_BUILD: nondebug # just the production-ready library testing
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3

      - name: Test procedure
        uses: ./.github/actions/docker_test_procedure
        with:
          config: ${{ matrix.CONFIG }} TEST_BUILD=${{ matrix.TEST_BUILD }}


  make_pkg:
    name: Packaging
    needs: in-tree
    runs-on: ubuntu-latest
    strategy:
      matrix:
        CONFIG: ${{ fromJSON(env.CONFIGS_JSON) }}
    steps:
      - name: Clone the git repo
        uses: actions/checkout@v3

      - name: Test procedure
        uses: ./.github/actions/docker_test_procedure
        with:
          config: ${{ matrix.CONFIG }} MAKE_PKG=1 VALGRIND=0
